CREATE TYPE "public"."date_format" AS ENUM('MM/DD/YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD');--> statement-breakpoint
CREATE TYPE "public"."language" AS ENUM('en', 'es', 'fr', 'de', 'it', 'pt', 'ja', 'ko', 'zh', 'ar');--> statement-breakpoint
CREATE TYPE "public"."org_role" AS ENUM('admin', 'worker');--> statement-breakpoint
CREATE TYPE "public"."permission" AS ENUM('read', 'write');--> statement-breakpoint
CREATE TYPE "public"."share_status" AS ENUM('private', 'shared_read', 'shared_write');--> statement-breakpoint
CREATE TYPE "public"."task_priority" AS ENUM('low', 'medium', 'high', 'urgent');--> statement-breakpoint
CREATE TYPE "public"."task_status" AS ENUM('pending', 'in_progress', 'completed', 'blocked');--> statement-breakpoint
CREATE TYPE "public"."theme" AS ENUM('light', 'dark', 'system');--> statement-breakpoint
CREATE TYPE "public"."usage_mode" AS ENUM('personal', 'organization');--> statement-breakpoint
CREATE TABLE "app_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "app_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "app_document_collaborators" (
	"id" serial PRIMARY KEY NOT NULL,
	"document_id" integer NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"last_edit" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"color" varchar(7) DEFAULT '#3B82F6' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_document_versions" (
	"id" serial PRIMARY KEY NOT NULL,
	"document_id" integer NOT NULL,
	"content" text NOT NULL,
	"annotations" json,
	"created_by_id" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_documents" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(256) NOT NULL,
	"content" text NOT NULL,
	"password_hash" varchar(256),
	"organization_id" integer,
	"created_by_id" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"annotations" json,
	"imported_from" varchar(256),
	"imported_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "app_event_comment" (
	"id" serial PRIMARY KEY NOT NULL,
	"text" text NOT NULL,
	"image_url" text,
	"event_id" integer NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_event_like" (
	"event_id" integer NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "app_event_like_event_id_createdById_pk" PRIMARY KEY("event_id","createdById")
);
--> statement-breakpoint
CREATE TABLE "app_event" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"image_url" text,
	"event_date" timestamp with time zone NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_note_collaborators" (
	"note_id" integer NOT NULL,
	"collaboratorId" varchar(255) NOT NULL,
	"permission" "permission" NOT NULL,
	CONSTRAINT "app_note_collaborators_note_id_collaboratorId_pk" PRIMARY KEY("note_id","collaboratorId")
);
--> statement-breakpoint
CREATE TABLE "app_organization_members" (
	"id" serial PRIMARY KEY NOT NULL,
	"organization_id" integer NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"role" "org_role" NOT NULL,
	"joined_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_organizations" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(256) NOT NULL,
	"access_code" varchar(14) NOT NULL,
	"created_by_id" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "app_organizations_access_code_unique" UNIQUE("access_code")
);
--> statement-breakpoint
CREATE TABLE "app_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "app_project_collaborators" (
	"project_id" integer NOT NULL,
	"collaboratorId" varchar(255) NOT NULL,
	"permission" "permission" NOT NULL,
	"joined_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "app_project_collaborators_project_id_collaboratorId_pk" PRIMARY KEY("project_id","collaboratorId")
);
--> statement-breakpoint
CREATE TABLE "app_projects" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" text,
	"createdById" varchar(255) NOT NULL,
	"share_status" "share_status" DEFAULT 'private' NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"organization_id" integer
);
--> statement-breakpoint
CREATE TABLE "app_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_sticky_notes" (
	"id" serial PRIMARY KEY NOT NULL,
	"content" text NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"password_hash" varchar(256),
	"password_salt" varchar(256),
	"reset_token" text,
	"reset_token_expiry" timestamp with time zone,
	"share_status" "share_status" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_task_activity_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"task_id" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"action" varchar(100) NOT NULL,
	"old_value" text,
	"new_value" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_task_comments" (
	"id" serial PRIMARY KEY NOT NULL,
	"content" text NOT NULL,
	"task_id" integer NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_tasks" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" text,
	"project_id" integer NOT NULL,
	"assignedToId" varchar(255),
	"status" "task_status" DEFAULT 'pending' NOT NULL,
	"priority" "task_priority" DEFAULT 'medium' NOT NULL,
	"due_date" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"createdById" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"order_index" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255),
	"usage_mode" "usage_mode",
	"password" varchar(255),
	"password_reset_token" varchar(255),
	"password_reset_expires" timestamp with time zone,
	"bio" text,
	"email_notifications" boolean DEFAULT true NOT NULL,
	"project_updates_notifications" boolean DEFAULT true NOT NULL,
	"event_reminders_notifications" boolean DEFAULT false NOT NULL,
	"marketing_emails_notifications" boolean DEFAULT false NOT NULL,
	"language" "language" DEFAULT 'en' NOT NULL,
	"timezone" varchar(100) DEFAULT 'UTC' NOT NULL,
	"date_format" date_format DEFAULT 'MM/DD/YYYY' NOT NULL,
	"theme" "theme" DEFAULT 'light' NOT NULL,
	"accent_color" varchar(20) DEFAULT 'indigo' NOT NULL,
	"profile_visibility" boolean DEFAULT true NOT NULL,
	"show_online_status" boolean DEFAULT true NOT NULL,
	"activity_tracking" boolean DEFAULT false NOT NULL,
	"data_collection" boolean DEFAULT false NOT NULL,
	"two_factor_enabled" boolean DEFAULT false NOT NULL,
	"two_factor_secret" varchar(255),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "app_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "app_account" ADD CONSTRAINT "app_account_userId_app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_document_collaborators" ADD CONSTRAINT "app_document_collaborators_document_id_app_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."app_documents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_document_collaborators" ADD CONSTRAINT "app_document_collaborators_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_document_versions" ADD CONSTRAINT "app_document_versions_document_id_app_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."app_documents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_document_versions" ADD CONSTRAINT "app_document_versions_created_by_id_app_user_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_documents" ADD CONSTRAINT "app_documents_organization_id_app_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."app_organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_documents" ADD CONSTRAINT "app_documents_created_by_id_app_user_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_event_comment" ADD CONSTRAINT "app_event_comment_event_id_app_event_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."app_event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_event_comment" ADD CONSTRAINT "app_event_comment_createdById_app_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_event_like" ADD CONSTRAINT "app_event_like_event_id_app_event_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."app_event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_event_like" ADD CONSTRAINT "app_event_like_createdById_app_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_event" ADD CONSTRAINT "app_event_createdById_app_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_note_collaborators" ADD CONSTRAINT "app_note_collaborators_note_id_app_sticky_notes_id_fk" FOREIGN KEY ("note_id") REFERENCES "public"."app_sticky_notes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_note_collaborators" ADD CONSTRAINT "app_note_collaborators_collaboratorId_app_user_id_fk" FOREIGN KEY ("collaboratorId") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_organization_members" ADD CONSTRAINT "app_organization_members_organization_id_app_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."app_organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_organization_members" ADD CONSTRAINT "app_organization_members_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_organizations" ADD CONSTRAINT "app_organizations_created_by_id_app_user_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_post" ADD CONSTRAINT "app_post_createdById_app_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_project_collaborators" ADD CONSTRAINT "app_project_collaborators_project_id_app_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."app_projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_project_collaborators" ADD CONSTRAINT "app_project_collaborators_collaboratorId_app_user_id_fk" FOREIGN KEY ("collaboratorId") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_projects" ADD CONSTRAINT "app_projects_createdById_app_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_projects" ADD CONSTRAINT "app_projects_organization_id_app_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."app_organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_session" ADD CONSTRAINT "app_session_userId_app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_sticky_notes" ADD CONSTRAINT "app_sticky_notes_createdById_app_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_task_activity_log" ADD CONSTRAINT "app_task_activity_log_task_id_app_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."app_tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_task_activity_log" ADD CONSTRAINT "app_task_activity_log_userId_app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_task_comments" ADD CONSTRAINT "app_task_comments_task_id_app_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."app_tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_task_comments" ADD CONSTRAINT "app_task_comments_createdById_app_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_tasks" ADD CONSTRAINT "app_tasks_project_id_app_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."app_projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_tasks" ADD CONSTRAINT "app_tasks_assignedToId_app_user_id_fk" FOREIGN KEY ("assignedToId") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_tasks" ADD CONSTRAINT "app_tasks_createdById_app_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "app_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "doc_collab_doc_idx" ON "app_document_collaborators" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "doc_collab_user_idx" ON "app_document_collaborators" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "doc_version_doc_idx" ON "app_document_versions" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "doc_version_created_idx" ON "app_document_versions" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "doc_created_by_idx" ON "app_documents" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX "doc_org_idx" ON "app_documents" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "comment_event_id_idx" ON "app_event_comment" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "comment_created_by_idx" ON "app_event_comment" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "like_event_id_idx" ON "app_event_like" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "event_created_by_idx" ON "app_event" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "event_date_idx" ON "app_event" USING btree ("event_date");--> statement-breakpoint
CREATE INDEX "collaborator_user_id_idx" ON "app_note_collaborators" USING btree ("collaboratorId");--> statement-breakpoint
CREATE INDEX "org_member_org_idx" ON "app_organization_members" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "org_member_user_idx" ON "app_organization_members" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "org_created_by_idx" ON "app_organizations" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX "org_access_code_idx" ON "app_organizations" USING btree ("access_code");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "app_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "app_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "project_collaborator_user_idx" ON "app_project_collaborators" USING btree ("collaboratorId");--> statement-breakpoint
CREATE INDEX "project_created_by_idx" ON "app_projects" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "project_org_idx" ON "app_projects" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "app_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "note_created_by_idx" ON "app_sticky_notes" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "activity_task_idx" ON "app_task_activity_log" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "activity_user_idx" ON "app_task_activity_log" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "task_comment_task_idx" ON "app_task_comments" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "task_comment_user_idx" ON "app_task_comments" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "task_project_idx" ON "app_tasks" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "task_assigned_to_idx" ON "app_tasks" USING btree ("assignedToId");--> statement-breakpoint
CREATE INDEX "task_created_by_idx" ON "app_tasks" USING btree ("createdById");